[package]
name = "fastanim-cli"
description = "The `fastanim` command-line tool"
version.workspace = true
edition.workspace = true
rust-version = "1.92"
license.workspace = true
repository.workspace = true

[[bin]]
name = "fastanim"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
clap_complete = "4.6.11"
fastanim-bevy.workspace = true
fastanim-core.workspace = true
fastanim-diff.workspace = true
fastanim-script = { workspace = true, features = ["metadata"] }
fastanim-text.workspace = true

[lints]
workspace = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/fastanim-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"
