[package]
name = "ranim-core"
description = "ranim core model: geometry, mobjects, animations and timeline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kurbo = "0.13"
ranim-diff.workspace = true

[lints]
workspace = true
