[package]
name = "ranim"
description = "Programmatic mathematical animation with diff-driven transforms"
version.workspace = true
edition.workspace = true
rust-version = "1.92"
license.workspace = true
repository.workspace = true

[dependencies]
ranim-diff.workspace = true
ranim-core.workspace = true
ranim-text.workspace = true

[lints]
workspace = true
