[package]
name = "ranim-cli"
description = "The `ranim` command-line tool"
version.workspace = true
edition.workspace = true
rust-version = "1.92"
license.workspace = true
repository.workspace = true

[[bin]]
name = "ranim"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
ranim-diff.workspace = true
ranim-text.workspace = true

[lints]
workspace = true
